import { float32LittleEndianBase64V1 } from '../replay-codegen.js';
import { canonicalRiverfallFluidInputJsonV1 } from '../../tools/studio/riverfall-fluid-config.js';
import type { RiverfallFluidTraceV1 } from './riverfall-fluid-simulation.js';

/** Emits the solver state immediately after canonical burn-in. */
export function riverfallFluidWarmStateSourceV1(
  trace: RiverfallFluidTraceV1,
): string {
  const state = trace.recordingInitialState;
  const encoded = {
    schemaVersion: 'studio.riverfall-fluid-warm-state/1',
    solver: trace.config.solver,
    particleCount: trace.config.particles.count,
    burnInSubsteps: trace.config.recording.burnInSubsteps,
    inputHash: `sha256:${trace.inputHash}`,
    canonicalInputJson: canonicalRiverfallFluidInputJsonV1(trace.config),
    longitudinalBase64: float32LittleEndianBase64V1(state.longitudinal),
    lateralBase64: float32LittleEndianBase64V1(state.lateral),
    longitudinalVelocityBase64:
      float32LittleEndianBase64V1(state.longitudinalVelocity),
    lateralVelocityBase64:
      float32LittleEndianBase64V1(state.lateralVelocity),
  } as const;
  return [
    '// Generated by fixtures/riverfall-consumer/riverfall-replay-generation.test.ts.',
    '// This is the canonical post-burn-in initial condition; every later pose is solved live.',
    "import { createRiverfallFluidConfigV1 } from './riverfall-fluid-config.js';",
    "import { decodeRiverfallFluidWarmStateV1 } from './riverfall-warm-state.js';",
    '',
    'export const RIVERFALL_FLUID_WARM_STATE_ENCODED_V1 =',
    `  ${JSON.stringify(encoded)} as const;`,
    '',
    'export const RIVERFALL_FLUID_WARM_STATE_V1 = decodeRiverfallFluidWarmStateV1(',
    '  RIVERFALL_FLUID_WARM_STATE_ENCODED_V1,',
    '  createRiverfallFluidConfigV1(),',
    ');',
    '',
  ].join('\n');
}
