import type { MachineWorksEventV1, MachineWorksTraceV1 } from './machine-works-simulation.js';

const REPLAY_ID = 'studio:pose-replay:machine-works';
const SCENE_ID = 'studio:scene:contrast-machines';

function base64(values: Float32Array): string {
  return Buffer.from(values.buffer, values.byteOffset, values.byteLength).toString('base64');
}

function requireBodyIds(event: MachineWorksEventV1, expected: readonly string[]): void {
  if (event.bodyIds.length !== expected.length
    || event.bodyIds.some((bodyId, index) => bodyId !== expected[index])) {
    throw new Error(
      `Cannot encode Machine Works '${event.kind}' event at tick ${String(event.tick)}: `
      + `expected bodyIds [${expected.join(', ')}], received [${event.bodyIds.join(', ')}]. `
      + 'Update the replay event mapping when the consumer assembly membership changes.',
    );
  }
}

function eventSource(event: MachineWorksEventV1, fixedStepMs: number): Record<string, unknown> {
  const common = {
    id: `machine-works:${event.kind}`,
    // Derive the event boundary with the exact same floating-point expression
    // as frame sampling. Rounding a repeating step such as 1000 / 60 upward
    // would make the event unavailable at its own recorded simulation tick.
    timeMs: event.tick * fixedStepMs,
  };
  switch (event.kind) {
    case 'assembled': {
      requireBodyIds(event, ['product-base', 'product-core', 'product-cap']);
      return {
        ...common,
        type: 'assembled',
        placementId: 'product-base',
        assemblyId: 'signal-module',
        memberPlacementIds: ['product-base', 'product-core', 'product-cap'],
      };
    }
    case 'released': {
      requireBodyIds(event, [
        'product-base', 'product-core', 'product-cap', 'assembly-carriage',
      ]);
      return {
        ...common,
        type: 'released',
        placementId: 'assembly-carriage',
        assemblyId: 'fixture:carriage-product',
        remainingMemberPlacementIds: ['product-base', 'product-core', 'product-cap'],
      };
    }
    case 'contact': {
      requireBodyIds(event, ['assembled-product', 'collection-bucket']);
      return {
        ...common,
        type: 'contact',
        placementId: 'product-base',
        otherPlacementId: 'collection-bucket',
        point: event.point,
        normal: event.normal,
        normalImpulse: event.normalImpulse,
      };
    }
    case 'collected': {
      requireBodyIds(event, ['assembled-product', 'collection-bucket']);
      return {
        ...common,
        type: 'collected',
        placementId: 'product-base',
        collectorPlacementId: 'collection-bucket',
      };
    }
  }
}

export function machineWorksReplaySourceV1(trace: MachineWorksTraceV1): string {
  const events = trace.events.map((event) => eventSource(event, trace.fixedStepMs));
  const encoded = {
    sceneId: SCENE_ID,
    frameCount: trace.frameCount,
    placementIds: trace.placementIds,
    provenance: {
      solver: trace.provenance.solver,
      fixedTimestepMs: trace.provenance.fixedTimestepMs,
      gravity: trace.provenance.gravity,
      inputHash: `sha256:${trace.provenance.inputHash}`,
      finalHash: `sha256:${trace.provenance.finalHash}`,
      lawLabels: trace.provenance.lawLabels,
      capabilityLabels: trace.provenance.capabilityLabels,
    },
    translationsBase64: base64(trace.translations),
    quaternionsBase64: base64(trace.rotations),
    linearVelocitiesBase64: base64(trace.linearVelocities),
    angularVelocitiesBase64: base64(trace.angularVelocities),
    events,
  };
  return [
    '// Generated by fixtures/machine-works-consumer/machine-works-replay-generation.test.ts.',
    '// The encoded values are consumer-solver observations; SceneSession defensively owns its copy.',
    "import { decodeInterleavedScenePoseReplayV1 } from './scene-pose-replay-codec.js';",
    '',
    `export const MACHINE_WORKS_POSE_REPLAY_ID = ${JSON.stringify(REPLAY_ID)};`,
    'export const MACHINE_WORKS_POSE_REPLAY = decodeInterleavedScenePoseReplayV1(',
    `${JSON.stringify(encoded)});`,
    '',
  ].join('\n');
}
