import { encodeReplayChannelsV1 } from '../replay-codegen.js';
import {
  WINDMILL_POSE_REPLAY_ID,
  WINDMILL_SCENE_ID,
} from '../../tools/studio/windmill-layout.js';
import {
  canonicalWindmillEvidenceJsonV1,
} from './windmill-evidence-hash.js';
import type {
  WindmillCompactRecordedTraceV1,
  WindmillCompactReplayEventV1,
} from './windmill-compact-recorder.js';
import {
  assertWindmillCompactRecordedTraceV1,
} from './windmill-compact-trace-integrity.js';


function eventSource(
  event: WindmillCompactReplayEventV1,
  solverStepSeconds: number,
): Readonly<Record<string, unknown>> {
  return {
    id: event.id,
    timeMs: event.tick * solverStepSeconds * 1_000,
    type: 'contact',
    placementId: event.primaryPlacementId,
    otherPlacementId: event.otherPlacementId,
    point: event.point,
    normal: event.normal,
    normalImpulse: event.normalImpulse,
  };
}

export function windmillReplaySourceV2(
  trace: WindmillCompactRecordedTraceV1,
): string {
  assertWindmillCompactRecordedTraceV1(trace);
  const encoded = {
    playback: 'once' as const,
    sceneId: WINDMILL_SCENE_ID,
    frameCount: trace.recordProfile.frameCount,
    placementIds: trace.placementIds,
    provenance: {
      ...trace.provenance,
      inputHash: `sha256:${trace.provenance.inputHash}`,
      finalHash: `sha256:${trace.provenance.finalHash}`,
    },
    ...encodeReplayChannelsV1({
      translations: trace.translations,
      quaternions: trace.rotations,
      linearVelocities: trace.linearVelocities,
      angularVelocities: trace.angularVelocities,
    }),
    events: trace.events.map((event) =>
      eventSource(event, trace.recordProfile.solverStepSeconds)),
  };
  return [
    '// Generated by fixtures/windmill-consumer/windmill-replay-generation.test.ts.',
    '// The finite pose channels are exact body-origin observations from the selected consumer-physics run.',
    '// Its two-sided relative-velocity pitched-plate rule is a bounded surrogate, not CFD, wake, or turbulence.',
    "import { decodeInterleavedScenePoseReplayV2 } from './scene-pose-replay-codec.js';",
    '',
    `export const WINDMILL_POSE_REPLAY_ID = ${JSON.stringify(WINDMILL_POSE_REPLAY_ID)};`,
    'export const WINDMILL_COMPACT_REPLAY_SELECTION = '
      + `${canonicalWindmillEvidenceJsonV1(trace.selection)} as const;`,
    'export const WINDMILL_COMPACT_REPLAY_RECORD_PROFILE = '
      + `${canonicalWindmillEvidenceJsonV1(trace.recordProfile)} as const;`,
    'export const WINDMILL_COMPACT_CANDIDATE_RESULT = '
      + `${canonicalWindmillEvidenceJsonV1(trace.evaluation.result)} as const;`,
    'export const WINDMILL_SIMULATION_EVIDENCE = '
      + `${canonicalWindmillEvidenceJsonV1(trace.evaluation.evidence)} as const;`,
    'export const WINDMILL_COMPACT_REPLAY_CONTACTS = '
      + `${canonicalWindmillEvidenceJsonV1(trace.events)} as const;`,
    'export const WINDMILL_POSE_REPLAY = decodeInterleavedScenePoseReplayV2(',
    `${JSON.stringify(encoded)});`,
    '',
  ].join('\n');
}
